/**
 * ViaNett Integration API
 * api.vianett.io
 *
 * OpenAPI spec version: v6
 * Contact: api@vianett.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ViaNettIntegrationApi) {
      root.ViaNettIntegrationApi = {};
    }
    root.ViaNettIntegrationApi.ContactDetails = factory(root.ViaNettIntegrationApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ContactDetails model module.
   * @module model/ContactDetails
   * @version v6
   */

  /**
   * Constructs a new <code>ContactDetails</code>.
   * @alias module:model/ContactDetails
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>ContactDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContactDetails} obj Optional instance to populate.
   * @return {module:model/ContactDetails} The populated <code>ContactDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('firstname')) {
        obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
      }
      if (data.hasOwnProperty('middlename')) {
        obj['middlename'] = ApiClient.convertToType(data['middlename'], 'String');
      }
      if (data.hasOwnProperty('lastname')) {
        obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
      }
      if (data.hasOwnProperty('streetAddress')) {
        obj['streetAddress'] = ApiClient.convertToType(data['streetAddress'], 'String');
      }
      if (data.hasOwnProperty('streetAddressZipCode')) {
        obj['streetAddressZipCode'] = ApiClient.convertToType(data['streetAddressZipCode'], 'String');
      }
      if (data.hasOwnProperty('streetCity')) {
        obj['streetCity'] = ApiClient.convertToType(data['streetCity'], 'String');
      }
      if (data.hasOwnProperty('dateBorn')) {
        obj['dateBorn'] = ApiClient.convertToType(data['dateBorn'], 'String');
      }
      if (data.hasOwnProperty('telephoneNr')) {
        obj['telephoneNr'] = ApiClient.convertToType(data['telephoneNr'], 'String');
      }
      if (data.hasOwnProperty('deathDate')) {
        obj['deathDate'] = ApiClient.convertToType(data['deathDate'], 'String');
      }
      if (data.hasOwnProperty('sex')) {
        obj['sex'] = ApiClient.convertToType(data['sex'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} firstname
   */
  exports.prototype['firstname'] = undefined;
  /**
   * @member {String} middlename
   */
  exports.prototype['middlename'] = undefined;
  /**
   * @member {String} lastname
   */
  exports.prototype['lastname'] = undefined;
  /**
   * @member {String} streetAddress
   */
  exports.prototype['streetAddress'] = undefined;
  /**
   * @member {String} streetAddressZipCode
   */
  exports.prototype['streetAddressZipCode'] = undefined;
  /**
   * @member {String} streetCity
   */
  exports.prototype['streetCity'] = undefined;
  /**
   * @member {String} dateBorn
   */
  exports.prototype['dateBorn'] = undefined;
  /**
   * @member {String} telephoneNr
   */
  exports.prototype['telephoneNr'] = undefined;
  /**
   * @member {String} deathDate
   */
  exports.prototype['deathDate'] = undefined;
  /**
   * @member {module:model/ContactDetails.SexEnum} sex
   */
  exports.prototype['sex'] = undefined;


  /**
   * Allowed values for the <code>sex</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SexEnum = {
    /**
     * value: "m"
     * @const
     */
    "m": "m",
    /**
     * value: "f"
     * @const
     */
    "f": "f"  };


  return exports;
}));


