/**
 * ViaNett Integration API
 * api.vianett.io
 *
 * OpenAPI spec version: v6
 * Contact: api@vianett.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ContactDetails'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ContactDetails'));
  } else {
    // Browser globals (root is window)
    if (!root.ViaNettIntegrationApi) {
      root.ViaNettIntegrationApi = {};
    }
    root.ViaNettIntegrationApi.ContactDetailsResult = factory(root.ViaNettIntegrationApi.ApiClient, root.ViaNettIntegrationApi.ContactDetails);
  }
}(this, function(ApiClient, ContactDetails) {
  'use strict';




  /**
   * The ContactDetailsResult model module.
   * @module model/ContactDetailsResult
   * @version v6
   */

  /**
   * Constructs a new <code>ContactDetailsResult</code>.
   * @alias module:model/ContactDetailsResult
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ContactDetailsResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContactDetailsResult} obj Optional instance to populate.
   * @return {module:model/ContactDetailsResult} The populated <code>ContactDetailsResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('primary')) {
        obj['primary'] = ContactDetails.constructFromObject(data['primary']);
      }
      if (data.hasOwnProperty('alternatives')) {
        obj['alternatives'] = ApiClient.convertToType(data['alternatives'], [ContactDetails]);
      }
    }
    return obj;
  }

  /**
   * The primary row is automatically selected from the alternatives on first retrieval.
   * @member {module:model/ContactDetails} primary
   */
  exports.prototype['primary'] = undefined;
  /**
   * Looking up a contact may return multiple rows
   * @member {Array.<module:model/ContactDetails>} alternatives
   */
  exports.prototype['alternatives'] = undefined;



  return exports;
}));


