/**
 * ViaNett Integration API
 * api.vianett.io
 *
 * OpenAPI spec version: v6
 * Contact: api@vianett.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ViaNettIntegrationApi) {
      root.ViaNettIntegrationApi = {};
    }
    root.ViaNettIntegrationApi.FreeOfChargeUser = factory(root.ViaNettIntegrationApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FreeOfChargeUser model module.
   * @module model/FreeOfChargeUser
   * @version v6
   */

  /**
   * Constructs a new <code>FreeOfChargeUser</code>.
   * @alias module:model/FreeOfChargeUser
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>FreeOfChargeUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FreeOfChargeUser} obj Optional instance to populate.
   * @return {module:model/FreeOfChargeUser} The populated <code>FreeOfChargeUser</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('companyId')) {
        obj['companyId'] = ApiClient.convertToType(data['companyId'], 'Integer');
      }
      if (data.hasOwnProperty('campaignId')) {
        obj['campaignId'] = ApiClient.convertToType(data['campaignId'], 'Integer');
      }
      if (data.hasOwnProperty('tel')) {
        obj['tel'] = ApiClient.convertToType(data['tel'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('comment')) {
        obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
      }
      if (data.hasOwnProperty('createdWhen')) {
        obj['createdWhen'] = ApiClient.convertToType(data['createdWhen'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The account for which the free of charge user setting applies (0 if all accounts)
   * @member {Integer} companyId
   */
  exports.prototype['companyId'] = undefined;
  /**
   * The CampaignId for which the free of charge user setting applies (0 if all campaigns for the CompanyId specified, or for all accounts if CompanyId is 0)
   * @member {Integer} campaignId
   */
  exports.prototype['campaignId'] = undefined;
  /**
   * The phone number for which the free of charge user setting applies
   * @member {Number} tel
   */
  exports.prototype['tel'] = undefined;
  /**
   * The name of the user for which the free of charge user setting applies
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The description of the reason why this is a free of charge user
   * @member {String} comment
   */
  exports.prototype['comment'] = undefined;
  /**
   * The date and time this setting was created
   * @member {Date} createdWhen
   */
  exports.prototype['createdWhen'] = undefined;



  return exports;
}));


