/**
 * ViaNett Integration API
 * api.vianett.io
 *
 * OpenAPI spec version: v6
 * Contact: api@vianett.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ViaNettIntegrationApi) {
      root.ViaNettIntegrationApi = {};
    }
    root.ViaNettIntegrationApi.KeywordCreateModel = factory(root.ViaNettIntegrationApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The KeywordCreateModel model module.
   * @module model/KeywordCreateModel
   * @version v6
   */

  /**
   * Constructs a new <code>KeywordCreateModel</code>.
   * @alias module:model/KeywordCreateModel
   * @class
   * @param accessNumber {Integer} 
   * @param mcc {Integer} 
   * @param prefix {String} 
   */
  var exports = function(accessNumber, mcc, prefix) {
    var _this = this;


    _this['accessNumber'] = accessNumber;
    _this['mcc'] = mcc;
    _this['prefix'] = prefix;


  };

  /**
   * Constructs a <code>KeywordCreateModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KeywordCreateModel} obj Optional instance to populate.
   * @return {module:model/KeywordCreateModel} The populated <code>KeywordCreateModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('companyId')) {
        obj['companyId'] = ApiClient.convertToType(data['companyId'], 'Integer');
      }
      if (data.hasOwnProperty('accessNumber')) {
        obj['accessNumber'] = ApiClient.convertToType(data['accessNumber'], 'Integer');
      }
      if (data.hasOwnProperty('mcc')) {
        obj['mcc'] = ApiClient.convertToType(data['mcc'], 'Integer');
      }
      if (data.hasOwnProperty('prefix')) {
        obj['prefix'] = ApiClient.convertToType(data['prefix'], 'String');
      }
      if (data.hasOwnProperty('campaignId')) {
        obj['campaignId'] = ApiClient.convertToType(data['campaignId'], 'Integer');
      }
      if (data.hasOwnProperty('serviceTypeId')) {
        obj['serviceTypeId'] = ApiClient.convertToType(data['serviceTypeId'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} companyId
   */
  exports.prototype['companyId'] = undefined;
  /**
   * @member {Integer} accessNumber
   */
  exports.prototype['accessNumber'] = undefined;
  /**
   * @member {Integer} mcc
   */
  exports.prototype['mcc'] = undefined;
  /**
   * @member {String} prefix
   */
  exports.prototype['prefix'] = undefined;
  /**
   * @member {Integer} campaignId
   */
  exports.prototype['campaignId'] = undefined;
  /**
   * Default 1000
   * @member {Integer} serviceTypeId
   */
  exports.prototype['serviceTypeId'] = undefined;



  return exports;
}));


