/**
 * ViaNett Integration API
 * api.vianett.io
 *
 * OpenAPI spec version: v6
 * Contact: api@vianett.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ViaNettIntegrationApi) {
      root.ViaNettIntegrationApi = {};
    }
    root.ViaNettIntegrationApi.Keyword = factory(root.ViaNettIntegrationApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Keyword model module.
   * @module model/Keyword
   * @version v6
   */

  /**
   * Constructs a new <code>Keyword</code>.
   * @alias module:model/Keyword
   * @class
   */
  var exports = function() {
    var _this = this;















  };

  /**
   * Constructs a <code>Keyword</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Keyword} obj Optional instance to populate.
   * @return {module:model/Keyword} The populated <code>Keyword</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('campaignId')) {
        obj['campaignId'] = ApiClient.convertToType(data['campaignId'], 'Integer');
      }
      if (data.hasOwnProperty('companyId')) {
        obj['companyId'] = ApiClient.convertToType(data['companyId'], 'Integer');
      }
      if (data.hasOwnProperty('accessNumber')) {
        obj['accessNumber'] = ApiClient.convertToType(data['accessNumber'], 'String');
      }
      if (data.hasOwnProperty('prefix')) {
        obj['prefix'] = ApiClient.convertToType(data['prefix'], 'String');
      }
      if (data.hasOwnProperty('serviceTypeId')) {
        obj['serviceTypeId'] = ApiClient.convertToType(data['serviceTypeId'], 'Integer');
      }
      if (data.hasOwnProperty('countryId')) {
        obj['countryId'] = ApiClient.convertToType(data['countryId'], 'Integer');
      }
      if (data.hasOwnProperty('establishmentFee')) {
        obj['establishmentFee'] = ApiClient.convertToType(data['establishmentFee'], 'Number');
      }
      if (data.hasOwnProperty('monthlyFee')) {
        obj['monthlyFee'] = ApiClient.convertToType(data['monthlyFee'], 'Number');
      }
      if (data.hasOwnProperty('numBillingMonths')) {
        obj['numBillingMonths'] = ApiClient.convertToType(data['numBillingMonths'], 'Integer');
      }
      if (data.hasOwnProperty('currency')) {
        obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
      }
      if (data.hasOwnProperty('paidUntil')) {
        obj['paidUntil'] = ApiClient.convertToType(data['paidUntil'], 'Date');
      }
      if (data.hasOwnProperty('paymentTypeId')) {
        obj['paymentTypeId'] = ApiClient.convertToType(data['paymentTypeId'], 'Integer');
      }
      if (data.hasOwnProperty('isLookupEnabled')) {
        obj['isLookupEnabled'] = ApiClient.convertToType(data['isLookupEnabled'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Primary key
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The campaign on which the keyword is configured
   * @member {Integer} campaignId
   */
  exports.prototype['campaignId'] = undefined;
  /**
   * The company id on which the keyword is configured
   * @member {Integer} companyId
   */
  exports.prototype['companyId'] = undefined;
  /**
   * The short code or long code on which the keyword is configured
   * @member {String} accessNumber
   */
  exports.prototype['accessNumber'] = undefined;
  /**
   * The keyword
   * @member {String} prefix
   */
  exports.prototype['prefix'] = undefined;
  /**
   * The type of service the keyword is configured as
   * @member {Integer} serviceTypeId
   */
  exports.prototype['serviceTypeId'] = undefined;
  /**
   * The country Id to which the AccessNumber belongs (0 is used for long codes, 1 for Norway, 2 for Sweden, 8 for Denmark, 105 for Finland, etc)
   * @member {Integer} countryId
   */
  exports.prototype['countryId'] = undefined;
  /**
   * The initial setup fee amount for this keyword
   * @member {Number} establishmentFee
   */
  exports.prototype['establishmentFee'] = undefined;
  /**
   * The monthly fee amount for this keyword
   * @member {Number} monthlyFee
   */
  exports.prototype['monthlyFee'] = undefined;
  /**
   * The billing frequency in months of the keyword
   * @member {Integer} numBillingMonths
   */
  exports.prototype['numBillingMonths'] = undefined;
  /**
   * The currency for the amounts specified in EstablishmentFee and MonthlyFee
   * @member {String} currency
   */
  exports.prototype['currency'] = undefined;
  /**
   * How long the keyword has been paid for thus far
   * @member {Date} paidUntil
   */
  exports.prototype['paidUntil'] = undefined;
  /**
   * The payment type (included, auto-charged, etc) for the keyword
   * @member {Integer} paymentTypeId
   */
  exports.prototype['paymentTypeId'] = undefined;
  /**
   * Whether a name and address lookup is triggered for incoming messages to this keyword
   * @member {Boolean} isLookupEnabled
   */
  exports.prototype['isLookupEnabled'] = undefined;



  return exports;
}));


