/**
 * ViaNett Integration API
 * api.vianett.io
 *
 * OpenAPI spec version: v6
 * Contact: api@vianett.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ContactDetailsResult', 'model/HlrLookupResult', 'model/MessageLogItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ContactDetailsResult'), require('./HlrLookupResult'), require('./MessageLogItem'));
  } else {
    // Browser globals (root is window)
    if (!root.ViaNettIntegrationApi) {
      root.ViaNettIntegrationApi = {};
    }
    root.ViaNettIntegrationApi.LookupResult = factory(root.ViaNettIntegrationApi.ApiClient, root.ViaNettIntegrationApi.ContactDetailsResult, root.ViaNettIntegrationApi.HlrLookupResult, root.ViaNettIntegrationApi.MessageLogItem);
  }
}(this, function(ApiClient, ContactDetailsResult, HlrLookupResult, MessageLogItem) {
  'use strict';




  /**
   * The LookupResult model module.
   * @module model/LookupResult
   * @version v6
   */

  /**
   * Constructs a new <code>LookupResult</code>.
   * LoopupApi result
   * @alias module:model/LookupResult
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>LookupResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LookupResult} obj Optional instance to populate.
   * @return {module:model/LookupResult} The populated <code>LookupResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('tel')) {
        obj['tel'] = ApiClient.convertToType(data['tel'], 'Integer');
      }
      if (data.hasOwnProperty('messages')) {
        obj['messages'] = ApiClient.convertToType(data['messages'], [MessageLogItem]);
      }
      if (data.hasOwnProperty('details')) {
        obj['details'] = ContactDetailsResult.constructFromObject(data['details']);
      }
      if (data.hasOwnProperty('hlr')) {
        obj['hlr'] = HlrLookupResult.constructFromObject(data['hlr']);
      }
    }
    return obj;
  }

  /**
   * @member {Integer} tel
   */
  exports.prototype['tel'] = undefined;
  /**
   * SMS log
   * @member {Array.<module:model/MessageLogItem>} messages
   */
  exports.prototype['messages'] = undefined;
  /**
   * Cached contact details
   * @member {module:model/ContactDetailsResult} details
   */
  exports.prototype['details'] = undefined;
  /**
   * Cached HLR result
   * @member {module:model/HlrLookupResult} hlr
   */
  exports.prototype['hlr'] = undefined;



  return exports;
}));


