/**
 * ViaNett Integration API
 * api.vianett.io
 *
 * OpenAPI spec version: v6
 * Contact: api@vianett.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SmsMessage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SmsMessage'));
  } else {
    // Browser globals (root is window)
    if (!root.ViaNettIntegrationApi) {
      root.ViaNettIntegrationApi = {};
    }
    root.ViaNettIntegrationApi.SmsMessageBatch = factory(root.ViaNettIntegrationApi.ApiClient, root.ViaNettIntegrationApi.SmsMessage);
  }
}(this, function(ApiClient, SmsMessage) {
  'use strict';




  /**
   * The SmsMessageBatch model module.
   * @module model/SmsMessageBatch
   * @version v6
   */

  /**
   * Constructs a new <code>SmsMessageBatch</code>.
   * @alias module:model/SmsMessageBatch
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SmsMessageBatch</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SmsMessageBatch} obj Optional instance to populate.
   * @return {module:model/SmsMessageBatch} The populated <code>SmsMessageBatch</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('batchId')) {
        obj['batchId'] = ApiClient.convertToType(data['batchId'], 'Integer');
      }
      if (data.hasOwnProperty('messages')) {
        obj['messages'] = ApiClient.convertToType(data['messages'], [SmsMessage]);
      }
    }
    return obj;
  }

  /**
   * An optional id for the whole batch
   * @member {Integer} batchId
   */
  exports.prototype['batchId'] = undefined;
  /**
   * One or more SMS messages
   * @member {Array.<module:model/SmsMessage>} messages
   */
  exports.prototype['messages'] = undefined;



  return exports;
}));


