/**
 * ViaNett Integration API
 * api.vianett.io
 *
 * OpenAPI spec version: v6
 * Contact: api@vianett.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NoContentResult', 'model/FreeOfChargeUser'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/NoContentResult'), require('../model/FreeOfChargeUser'));
  } else {
    // Browser globals (root is window)
    if (!root.ViaNettIntegrationApi) {
      root.ViaNettIntegrationApi = {};
    }
    root.ViaNettIntegrationApi.FreeOfChargeUserApi = factory(root.ViaNettIntegrationApi.ApiClient, root.ViaNettIntegrationApi.NoContentResult, root.ViaNettIntegrationApi.FreeOfChargeUser);
  }
}(this, function(ApiClient, NoContentResult, FreeOfChargeUser) {
  'use strict';

  /**
   * FreeOfChargeUser service.
   * @module api/FreeOfChargeUserApi
   * @version v6
   */

  /**
   * Constructs a new FreeOfChargeUserApi. 
   * @alias module:api/FreeOfChargeUserApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the testTelByIdDelete operation.
     * @callback module:api/FreeOfChargeUserApi~testTelByIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/NoContentResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete free of charge user
     * @param {Integer} id 
     * @param {module:api/FreeOfChargeUserApi~testTelByIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/NoContentResult}
     */
    this.testTelByIdDelete = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling testTelByIdDelete";
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = NoContentResult;

      return this.apiClient.callApi(
        '/test-tel/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the testTelByIdGet operation.
     * @callback module:api/FreeOfChargeUserApi~testTelByIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/FreeOfChargeUser} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get free of charge user
     * @param {Integer} id 
     * @param {module:api/FreeOfChargeUserApi~testTelByIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/FreeOfChargeUser}
     */
    this.testTelByIdGet = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling testTelByIdGet";
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = FreeOfChargeUser;

      return this.apiClient.callApi(
        '/test-tel/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the testTelGet operation.
     * @callback module:api/FreeOfChargeUserApi~testTelGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/FreeOfChargeUser>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List free of charge users
     * @param {Object} opts Optional parameters
     * @param {Integer} opts.companyId Default is current account
     * @param {module:api/FreeOfChargeUserApi~testTelGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/FreeOfChargeUser>}
     */
    this.testTelGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'companyId': opts['companyId']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [FreeOfChargeUser];

      return this.apiClient.callApi(
        '/test-tel', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the testTelPost operation.
     * @callback module:api/FreeOfChargeUserApi~testTelPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/FreeOfChargeUser} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add free of charge user
     * @param {Object} opts Optional parameters
     * @param {module:model/FreeOfChargeUser} opts.value 
     * @param {module:api/FreeOfChargeUserApi~testTelPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/FreeOfChargeUser}
     */
    this.testTelPost = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['value'];


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json', 'text/json', 'application/json-patch+json'];
      var accepts = ['application/json'];
      var returnType = FreeOfChargeUser;

      return this.apiClient.callApi(
        '/test-tel', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
