/**
 * ViaNett Integration API
 * api.vianett.io
 *
 * OpenAPI spec version: v6
 * Contact: api@vianett.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ContactDetailsResult', 'model/ContactDetails', 'model/LookupResult', 'model/HlrLookupResult', 'model/MessageLogItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ContactDetailsResult'), require('../model/ContactDetails'), require('../model/LookupResult'), require('../model/HlrLookupResult'), require('../model/MessageLogItem'));
  } else {
    // Browser globals (root is window)
    if (!root.ViaNettIntegrationApi) {
      root.ViaNettIntegrationApi = {};
    }
    root.ViaNettIntegrationApi.LookupApi = factory(root.ViaNettIntegrationApi.ApiClient, root.ViaNettIntegrationApi.ContactDetailsResult, root.ViaNettIntegrationApi.ContactDetails, root.ViaNettIntegrationApi.LookupResult, root.ViaNettIntegrationApi.HlrLookupResult, root.ViaNettIntegrationApi.MessageLogItem);
  }
}(this, function(ApiClient, ContactDetailsResult, ContactDetails, LookupResult, HlrLookupResult, MessageLogItem) {
  'use strict';

  /**
   * Lookup service.
   * @module api/LookupApi
   * @version v6
   */

  /**
   * Constructs a new LookupApi. 
   * @alias module:api/LookupApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the lookupByTelDetailsGet operation.
     * @callback module:api/LookupApi~lookupByTelDetailsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ContactDetailsResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return details for tel
     * @param {Integer} tel Phone number with country code
     * @param {Object} opts Optional parameters
     * @param {Integer} opts.companyId Default is current account
     * @param {module:api/LookupApi~lookupByTelDetailsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ContactDetailsResult}
     */
    this.lookupByTelDetailsGet = function(tel, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'tel' is set
      if (tel == undefined || tel == null) {
        throw "Missing the required parameter 'tel' when calling lookupByTelDetailsGet";
      }


      var pathParams = {
        'tel': tel
      };
      var queryParams = {
        'companyId': opts['companyId']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = ContactDetailsResult;

      return this.apiClient.callApi(
        '/lookup/{tel}/details', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the lookupByTelDetailsPut operation.
     * @callback module:api/LookupApi~lookupByTelDetailsPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update primary contact details for tel
     * @param {Integer} tel Phone number with country code
     * @param {Object} opts Optional parameters
     * @param {module:model/ContactDetails} opts.value 
     * @param {Integer} opts.companyId Default is current account
     * @param {module:api/LookupApi~lookupByTelDetailsPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.lookupByTelDetailsPut = function(tel, opts, callback) {
      opts = opts || {};
      var postBody = opts['value'];

      // verify the required parameter 'tel' is set
      if (tel == undefined || tel == null) {
        throw "Missing the required parameter 'tel' when calling lookupByTelDetailsPut";
      }


      var pathParams = {
        'tel': tel
      };
      var queryParams = {
        'companyId': opts['companyId']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json', 'text/json', 'application/json-patch+json'];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/lookup/{tel}/details', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the lookupByTelGet operation.
     * @callback module:api/LookupApi~lookupByTelGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LookupResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return all known data for tel
     * @param {Integer} tel Phone number with country code
     * @param {Object} opts Optional parameters
     * @param {Integer} opts.companyId Default is current account
     * @param {module:api/LookupApi~lookupByTelGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LookupResult}
     */
    this.lookupByTelGet = function(tel, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'tel' is set
      if (tel == undefined || tel == null) {
        throw "Missing the required parameter 'tel' when calling lookupByTelGet";
      }


      var pathParams = {
        'tel': tel
      };
      var queryParams = {
        'companyId': opts['companyId']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = LookupResult;

      return this.apiClient.callApi(
        '/lookup/{tel}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the lookupByTelHlrGet operation.
     * @callback module:api/LookupApi~lookupByTelHlrGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HlrLookupResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * HLR lookup
     * @param {Integer} tel Phone number with country code
     * @param {Object} opts Optional parameters
     * @param {Integer} opts.maxAgeInSeconds Run live HLR request if cached entry is older than N seconds. Default is 48 hours. Set to 0 to disable cache
     * @param {Integer} opts.companyId Default is current account
     * @param {module:api/LookupApi~lookupByTelHlrGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HlrLookupResult}
     */
    this.lookupByTelHlrGet = function(tel, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'tel' is set
      if (tel == undefined || tel == null) {
        throw "Missing the required parameter 'tel' when calling lookupByTelHlrGet";
      }


      var pathParams = {
        'tel': tel
      };
      var queryParams = {
        'maxAgeInSeconds': opts['maxAgeInSeconds'],
        'companyId': opts['companyId']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = HlrLookupResult;

      return this.apiClient.callApi(
        '/lookup/{tel}/hlr', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the lookupByTelLogsGet operation.
     * @callback module:api/LookupApi~lookupByTelLogsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/MessageLogItem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return SMS logs for tel
     * @param {Integer} tel Phone number with country code
     * @param {Object} opts Optional parameters
     * @param {Integer} opts.companyId Default is current account
     * @param {module:api/LookupApi~lookupByTelLogsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/MessageLogItem>}
     */
    this.lookupByTelLogsGet = function(tel, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'tel' is set
      if (tel == undefined || tel == null) {
        throw "Missing the required parameter 'tel' when calling lookupByTelLogsGet";
      }


      var pathParams = {
        'tel': tel
      };
      var queryParams = {
        'companyId': opts['companyId']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [MessageLogItem];

      return this.apiClient.callApi(
        '/lookup/{tel}/logs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
