/**
 * ViaNett Integration API
 * api.vianett.io
 *
 * OpenAPI spec version: v6
 * Contact: api@vianett.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SmsMessageBatch', 'model/SmsMessage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/SmsMessageBatch'), require('../model/SmsMessage'));
  } else {
    // Browser globals (root is window)
    if (!root.ViaNettIntegrationApi) {
      root.ViaNettIntegrationApi = {};
    }
    root.ViaNettIntegrationApi.SendSmsApi = factory(root.ViaNettIntegrationApi.ApiClient, root.ViaNettIntegrationApi.SmsMessageBatch, root.ViaNettIntegrationApi.SmsMessage);
  }
}(this, function(ApiClient, SmsMessageBatch, SmsMessage) {
  'use strict';

  /**
   * SendSms service.
   * @module api/SendSmsApi
   * @version v6
   */

  /**
   * Constructs a new SendSmsApi. 
   * @alias module:api/SendSmsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the sendsmsBatchPost operation.
     * @callback module:api/SendSmsApi~sendsmsBatchPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Send a batch of messages
     * @param {Object} opts Optional parameters
     * @param {module:model/SmsMessageBatch} opts.body 
     * @param {module:api/SendSmsApi~sendsmsBatchPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.sendsmsBatchPost = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json', 'text/json', 'application/json-patch+json'];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/sendsms/batch', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the sendsmsPost operation.
     * @callback module:api/SendSmsApi~sendsmsPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Send a single message
     * @param {Object} opts Optional parameters
     * @param {module:model/SmsMessage} opts.body 
     * @param {module:api/SendSmsApi~sendsmsPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.sendsmsPost = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json', 'text/json', 'application/json-patch+json'];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/sendsms', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the sendsmsSimpleGet operation.
     * @callback module:api/SendSmsApi~sendsmsSimpleGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Send SMS using a plain GET request without OAuth2
     * @param {Object} opts Optional parameters
     * @param {String} opts.username 
     * @param {String} opts.password 
     * @param {module:api/SendSmsApi~sendsmsSimpleGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.sendsmsSimpleGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'username': opts['username'],
        'password': opts['password']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/sendsms/simple', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
