/**
 * ViaNett Integration API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ViaNettIntegrationApi);
  }
}(this, function(expect, ViaNettIntegrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ViaNettIntegrationApi.Company();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Company', function() {
    it('should create an instance of Company', function() {
      // uncomment below and update the code to test Company
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be.a(ViaNettIntegrationApi.Company);
    });

    it('should have the property companyId (base name: "companyId")', function() {
      // uncomment below and update the code to test the property companyId
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property motherCompanyId (base name: "motherCompanyId")', function() {
      // uncomment below and update the code to test the property motherCompanyId
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property mainCompanyId (base name: "mainCompanyId")', function() {
      // uncomment below and update the code to test the property mainCompanyId
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property disabled (base name: "disabled")', function() {
      // uncomment below and update the code to test the property disabled
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property demo (base name: "demo")', function() {
      // uncomment below and update the code to test the property demo
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property fromMcc (base name: "fromMcc")', function() {
      // uncomment below and update the code to test the property fromMcc
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property fromNrEnabled (base name: "fromNrEnabled")', function() {
      // uncomment below and update the code to test the property fromNrEnabled
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property pricegroupEnabled (base name: "pricegroupEnabled")', function() {
      // uncomment below and update the code to test the property pricegroupEnabled
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property locationServiceEnabled (base name: "locationServiceEnabled")', function() {
      // uncomment below and update the code to test the property locationServiceEnabled
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property msgLimitEnabled (base name: "msgLimitEnabled")', function() {
      // uncomment below and update the code to test the property msgLimitEnabled
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property balanceLimitEnabled (base name: "balanceLimitEnabled")', function() {
      // uncomment below and update the code to test the property balanceLimitEnabled
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property hidePricesEnabled (base name: "hidePricesEnabled")', function() {
      // uncomment below and update the code to test the property hidePricesEnabled
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property postalAddress (base name: "postalAddress")', function() {
      // uncomment below and update the code to test the property postalAddress
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property postalZip (base name: "postalZip")', function() {
      // uncomment below and update the code to test the property postalZip
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property postalCity (base name: "postalCity")', function() {
      // uncomment below and update the code to test the property postalCity
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property postalCountry (base name: "postalCountry")', function() {
      // uncomment below and update the code to test the property postalCountry
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property homepage (base name: "homepage")', function() {
      // uncomment below and update the code to test the property homepage
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property customerSupportEmail (base name: "customerSupportEmail")', function() {
      // uncomment below and update the code to test the property customerSupportEmail
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property technicalContactEmail (base name: "technicalContactEmail")', function() {
      // uncomment below and update the code to test the property technicalContactEmail
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property technicalContactPhone (base name: "technicalContactPhone")', function() {
      // uncomment below and update the code to test the property technicalContactPhone
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property autoResponseEmail (base name: "autoResponseEmail")', function() {
      // uncomment below and update the code to test the property autoResponseEmail
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property defaultConnectionId (base name: "defaultConnectionId")', function() {
      // uncomment below and update the code to test the property defaultConnectionId
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property defaultCampaignId (base name: "defaultCampaignId")', function() {
      // uncomment below and update the code to test the property defaultCampaignId
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

    it('should have the property sendAlertInvalidMsisdnEnabled (base name: "sendAlertInvalidMsisdnEnabled")', function() {
      // uncomment below and update the code to test the property sendAlertInvalidMsisdnEnabled
      //var instane = new ViaNettIntegrationApi.Company();
      //expect(instance).to.be();
    });

  });

}));
