/**
 * ViaNett Integration API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ViaNettIntegrationApi);
  }
}(this, function(expect, ViaNettIntegrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ViaNettIntegrationApi.Connection();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Connection', function() {
    it('should create an instance of Connection', function() {
      // uncomment below and update the code to test Connection
      //var instane = new ViaNettIntegrationApi.Connection();
      //expect(instance).to.be.a(ViaNettIntegrationApi.Connection);
    });

    it('should have the property connectionId (base name: "connectionId")', function() {
      // uncomment below and update the code to test the property connectionId
      //var instane = new ViaNettIntegrationApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property companyId (base name: "companyId")', function() {
      // uncomment below and update the code to test the property companyId
      //var instane = new ViaNettIntegrationApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new ViaNettIntegrationApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instane = new ViaNettIntegrationApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instane = new ViaNettIntegrationApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property priorityOffset (base name: "priorityOffset")', function() {
      // uncomment below and update the code to test the property priorityOffset
      //var instane = new ViaNettIntegrationApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property defaultCampaignId (base name: "defaultCampaignId")', function() {
      // uncomment below and update the code to test the property defaultCampaignId
      //var instane = new ViaNettIntegrationApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property httpMoUrl (base name: "httpMoUrl")', function() {
      // uncomment below and update the code to test the property httpMoUrl
      //var instane = new ViaNettIntegrationApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property httpMoIncludeFullMsg (base name: "httpMoIncludeFullMsg")', function() {
      // uncomment below and update the code to test the property httpMoIncludeFullMsg
      //var instane = new ViaNettIntegrationApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property httpDrUrl (base name: "httpDrUrl")', function() {
      // uncomment below and update the code to test the property httpDrUrl
      //var instane = new ViaNettIntegrationApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property httpDrExtended (base name: "httpDrExtended")', function() {
      // uncomment below and update the code to test the property httpDrExtended
      //var instane = new ViaNettIntegrationApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property httpPost (base name: "httpPost")', function() {
      // uncomment below and update the code to test the property httpPost
      //var instane = new ViaNettIntegrationApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property httpQueryStringEncoding (base name: "httpQueryStringEncoding")', function() {
      // uncomment below and update the code to test the property httpQueryStringEncoding
      //var instane = new ViaNettIntegrationApi.Connection();
      //expect(instance).to.be();
    });

  });

}));
