/**
 * ViaNett Integration API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ViaNettIntegrationApi);
  }
}(this, function(expect, ViaNettIntegrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ViaNettIntegrationApi.Keyword();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Keyword', function() {
    it('should create an instance of Keyword', function() {
      // uncomment below and update the code to test Keyword
      //var instane = new ViaNettIntegrationApi.Keyword();
      //expect(instance).to.be.a(ViaNettIntegrationApi.Keyword);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new ViaNettIntegrationApi.Keyword();
      //expect(instance).to.be();
    });

    it('should have the property campaignId (base name: "campaignId")', function() {
      // uncomment below and update the code to test the property campaignId
      //var instane = new ViaNettIntegrationApi.Keyword();
      //expect(instance).to.be();
    });

    it('should have the property companyId (base name: "companyId")', function() {
      // uncomment below and update the code to test the property companyId
      //var instane = new ViaNettIntegrationApi.Keyword();
      //expect(instance).to.be();
    });

    it('should have the property accessNumber (base name: "accessNumber")', function() {
      // uncomment below and update the code to test the property accessNumber
      //var instane = new ViaNettIntegrationApi.Keyword();
      //expect(instance).to.be();
    });

    it('should have the property prefix (base name: "prefix")', function() {
      // uncomment below and update the code to test the property prefix
      //var instane = new ViaNettIntegrationApi.Keyword();
      //expect(instance).to.be();
    });

    it('should have the property serviceTypeId (base name: "serviceTypeId")', function() {
      // uncomment below and update the code to test the property serviceTypeId
      //var instane = new ViaNettIntegrationApi.Keyword();
      //expect(instance).to.be();
    });

    it('should have the property countryId (base name: "countryId")', function() {
      // uncomment below and update the code to test the property countryId
      //var instane = new ViaNettIntegrationApi.Keyword();
      //expect(instance).to.be();
    });

    it('should have the property establishmentFee (base name: "establishmentFee")', function() {
      // uncomment below and update the code to test the property establishmentFee
      //var instane = new ViaNettIntegrationApi.Keyword();
      //expect(instance).to.be();
    });

    it('should have the property monthlyFee (base name: "monthlyFee")', function() {
      // uncomment below and update the code to test the property monthlyFee
      //var instane = new ViaNettIntegrationApi.Keyword();
      //expect(instance).to.be();
    });

    it('should have the property numBillingMonths (base name: "numBillingMonths")', function() {
      // uncomment below and update the code to test the property numBillingMonths
      //var instane = new ViaNettIntegrationApi.Keyword();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new ViaNettIntegrationApi.Keyword();
      //expect(instance).to.be();
    });

    it('should have the property paidUntil (base name: "paidUntil")', function() {
      // uncomment below and update the code to test the property paidUntil
      //var instane = new ViaNettIntegrationApi.Keyword();
      //expect(instance).to.be();
    });

    it('should have the property paymentTypeId (base name: "paymentTypeId")', function() {
      // uncomment below and update the code to test the property paymentTypeId
      //var instane = new ViaNettIntegrationApi.Keyword();
      //expect(instance).to.be();
    });

    it('should have the property isLookupEnabled (base name: "isLookupEnabled")', function() {
      // uncomment below and update the code to test the property isLookupEnabled
      //var instane = new ViaNettIntegrationApi.Keyword();
      //expect(instance).to.be();
    });

  });

}));
